version: '3.8'

# Professional Prosody XMPP Server - TURN/STUN Server
# Coturn server for WebRTC support in XMPP

services:
  # ============================================================================
  # COTURN - TURN/STUN SERVER
  # ============================================================================
  coturn:
    image: coturn/coturn:latest
    container_name: prosody-coturn
    restart: unless-stopped
    
    ports:
      # STUN/TURN ports
      - '${TURN_PORT:-3478}:3478'
      - '${TURN_PORT:-3478}:3478/udp'
      - '${TURNS_PORT:-5349}:5349'
      - '${TURNS_PORT:-5349}:5349/udp'
      # Relay ports range
      - '${TURN_MIN_PORT:-49152}-${TURN_MAX_PORT:-65535}:49152-65535/udp'
    
    environment:
      # Basic configuration
      - TURN_DOMAIN=${PROSODY_DOMAIN:-localhost}
      - TURN_REALM=${PROSODY_DOMAIN:-localhost}
      
      # Authentication
      - TURN_USERNAME=${TURN_USERNAME:-prosody}
      - TURN_PASSWORD=${TURN_PASSWORD:-changeme}
      - TURN_SECRET=${TURN_SECRET:-changeme}
      
      # Security settings
      - TURN_NO_LOOPBACK_PEERS=true
      - TURN_NO_MULTICAST_PEERS=true
      - TURN_STALE_NONCE=true
      - TURN_SECURE_STUN=true
      
      # Logging
      - TURN_LOG_FILE=stdout
      - TURN_VERBOSE=false
    
    volumes:
      - ./turn/turnserver.conf:/etc/turnserver.conf:ro
      - coturn_data:/var/lib/coturn
    
    command: >
      sh -c "
        echo 'Configuring Coturn server...' &&
        turnserver
          --listening-port=3478
          --tls-listening-port=5349
          --min-port=49152
          --max-port=65535
          --realm=$${TURN_REALM}
          --server-name=$${TURN_DOMAIN}
          --lt-cred-mech
          --user=$${TURN_USERNAME}:$${TURN_PASSWORD}
          --use-auth-secret
          --static-auth-secret=$${TURN_SECRET}
          --no-loopback-peers
          --no-multicast-peers
          --mobility
          --no-cli
          --no-tlsv1
          --no-tlsv1_1
          --cipher-list='ECDHE+AESGCM:ECDHE+CHACHA20:DHE+AESGCM:DHE+CHACHA20:!aNULL:!MD5:!DSS'
          --no-sslv2
          --no-sslv3
          --dh-file=/etc/ssl/certs/dhparam.pem
          --cert=/etc/ssl/certs/$${TURN_DOMAIN}.pem
          --pkey=/etc/ssl/private/$${TURN_DOMAIN}.key
          --log-file=stdout
          --simple-log
      "
    
    networks:
      - prosody_network
      - turn_network
    
    # Security settings
    security_opt:
      - no-new-privileges:true
    
    # Resource limits
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: '1.0'
        reservations:
          memory: 64M
          cpus: '0.25'
    
    profiles:
      - turn
      - webrtc

  # ============================================================================
  # SIMPLE STUN SERVER (Alternative/Backup)
  # ============================================================================
  stun-server:
    image: instrumentisto/coturn:latest
    container_name: prosody-stun
    restart: unless-stopped
    
    ports:
      - '${STUN_PORT:-19302}:19302/udp'
    
    command: >
      turnserver
        --listening-port=19302
        --realm=${PROSODY_DOMAIN:-localhost}
        --server-name=${PROSODY_DOMAIN:-localhost}
        --stun-only
        --no-cli
        --log-file=stdout
        --simple-log
        --verbose
    
    networks:
      - turn_network
    
    profiles:
      - stun
      - webrtc

  # ============================================================================
  # TURN SERVER MONITORING
  # ============================================================================
  turn-monitor:
    build:
      context: ./monitoring/turn-monitor
      dockerfile: Dockerfile
    container_name: prosody-turn-monitor
    restart: unless-stopped
    
    environment:
      - TURN_HOST=coturn
      - TURN_PORT=3478
      - TURN_USERNAME=${TURN_USERNAME:-prosody}
      - TURN_PASSWORD=${TURN_PASSWORD:-changeme}
      - MONITOR_INTERVAL=30
    
    depends_on:
      - coturn
    
    networks:
      - turn_network
      - monitoring_network
    
    profiles:
      - turn
      - monitoring

# ============================================================================
# TURN/STUN VOLUMES
# ============================================================================
volumes:
  coturn_data:
    driver: local

# ============================================================================
# TURN/STUN NETWORKS
# ============================================================================
networks:
  turn_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.22.0.0/16 