name: Shellcheck and Format

on:
  push:
    branches: [ main, develop ]
    paths:
      - '**/*.sh'
      - 'prosody-manager'
  pull_request:
    branches: [ main, develop ]
    paths:
      - '**/*.sh'
      - 'prosody-manager'

jobs:
  shellcheck:
    name: Shellcheck
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Run shellcheck
        uses: ludeeus/action-shellcheck@master
        with:
          scandir: './scripts'
          additional_files: 'prosody-manager'
          severity: error
          
  shfmt:
    name: Shell Format Check
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Install shfmt
        run: |
          go install mvdan.cc/sh/v3/cmd/shfmt@latest
          echo "$HOME/go/bin" >> $GITHUB_PATH
          
      - name: Check shell script formatting
        run: |
          # Find all shell scripts
          files=$(find . -name "*.sh" -o -name "prosody-manager" | grep -v ".git")
          
          # Check formatting (4 spaces, case indentation)
          if ! shfmt -d -i 4 -ci $files; then
            echo "❌ Shell scripts are not properly formatted"
            echo "Run 'shfmt -w -i 4 -ci .' to fix formatting"
            exit 1
          fi
          
          echo "✅ All shell scripts are properly formatted" 